AllCops:
  TargetRubyVersion: 2.2

  Exclude:
    - 'bin/**/*'

# Rubocop and I cannot agree.
Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Lint/RescueWithoutErrorClass:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

# We like to use the hash rocket in rake files.
Style/HashSyntax:
  Exclude:
    - 'Rakefile'

# We'll just use double quotes everywhere.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# I prefer not to use %i or %I for an array of symbols.
Style/SymbolArray:
  Enabled: false

# We are not going to optimize by freezing strings.
Style/MutableConstant:
  Enabled: false
