require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

  Exclude:
    - 'bin/**/*'

# Rubocop and I cannot agree.
Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

Metrics/LineLength:
  Max: 120

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/LeadingSubject:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/SubjectStub:
  Enabled: false

# We can ignore this small performance improvement.
Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# We like to use the hash rocket in rake files.
Style/HashSyntax:
  Exclude:
    - 'Rakefile'

# No need to mention StandardError.
Style/RescueStandardError:
  EnforcedStyle: implicit

# We'll just use double quotes everywhere.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# I prefer not to use %i or %I for an array of symbols.
Style/SymbolArray:
  Enabled: false

# We are not going to optimize by freezing strings.
Style/MutableConstant:
  Enabled: false
